SCREEN_SIZE = 1920, 1080
SCREEN_WIDTH, SCREEN_HEIGHT = SCREEN_SIZE

TARGET_FPS = 0

CHUNK_SIZE = 8, 8
CHUNK_WIDTH, CHUNK_HEIGHT = CHUNK_SIZE

WORLD_SIZE = 30, 25  # in chunks
WORLD_WIDTH, WORLD_HEIGHT = WORLD_SIZE

EDGE_SCROLLING_PERCENT = 0.00  # makes zone for edge scrolling

TOP_BAR_HEIGHT = 32

HUD_ITEM_SIZE = 64, 64
HUD_ITEM_IMAGE_SIZE = 60, 60
HUD_ITEM_PADDING = 2, 2
HUD_ITEM_MARGIN = 8
BOTTOM_MENU_HEIGHT = 2 * (HUD_ITEM_SIZE[1] + HUD_ITEM_MARGIN) + HUD_ITEM_MARGIN  # heights is 2 items
